### ISSUE TITLE
Status of the extension

### ISSUE THREAD

**Issue by stof** [Behat/ChainedStepsExtension#2]
This extension was started as an experiment to reintroduce chained steps in Behat 3 based on the initial refactoring (beta versions). It was never really completed. The composer.json file was not even valid.

It is now incompatible with the current state of Behat because of the second rewrite between beta8 and RC1.
I started the work of rewriting the extension for Behat 3-RC, but I haven't found the right way to implement things yet. These substeps simply don't seem to fit well with the new architecture.
the first question is whether we really want to provide such extension for Behat 3. Are we reimplementing it or are we teaching people about a cleaner way to reuse code in their contexts ?

what do you think about it @everzet ?

and if we decide to implement this extension properly, I would appreciate a pointer if you have an idea about the implementation in the new system

**Comment by stof** [comment]
If we decide to keep the extensions, some steps will be required:
- registering it on Packagist
- enabling Travis on it (I already added a config file in it)
- potentially enabling Scrutinizer (it is not enabled yet for other extensions either but I would like it)

If anyone is interested, I pushed my current work on Github already: https://github.com/stof/ChainedStepsExtension/compare/Behat:master...stof:update_extension
My attempts at reimplementing the chained steps are not committed as they don't work

**Comment by weaverryan** [comment]
FWIW, I _do_ use chained steps in Behat currently - I use them quite a bit :). One that I (and other people I show it to) love is multi-part steps (Given I login - which actually does about 5 things).

I know that when architecture changes, the _old_ way of accomplishing something isn't necessarily the best _new_ way. So if this isn't the right way, what way should we be teaching people?

Thanks @stof for poking this :)

**Comment by stof** [comment]
Reimplementing this extension for Behat 3.0-RC is blocked by https://github.com/Behat/Behat/issues/443

**Comment by robocoder** [comment]
We use chained steps quite a bit too.  Moreover, I submitted a feature request for Behat 2.x to report sub-steps (i.e., useful for debugging a failed multi-part step).

**Comment by stof** [comment]
I agree we should try to keep it. and the good news is that @everzet announced that he has an idea to solve the blocker

**Comment by jverdeyen** [comment]
Any update on this?

**Comment by jverdeyen** [comment]
Any update on this? Can I use Reusable actions with Behat 3.0?

**Comment by stof** [comment]
I haven't add time to finish the rewrite yet. The WIP is in https://github.com/Behat/ChainedStepsExtension/pull/3

**Comment by adrienbrault** [comment]
@stof What is left to do ? i18n ? (The existing features are confusing)

**Comment by stof** [comment]
@adrienbrault Actually, some more features should be added which don't use i18n to see better if it works for the simple case. The existing features are indeed confusing. I don't know exactly hw much is missing and how much works (I haven't spent time on it to finish it as I'm quite busy)

**Comment by jhedstrom** [comment]
FWIW, the Drupal Extension, with a port underway to Behat 3, is also a heavy user of chained steps as simple additions to those provided by the Mink Extension.

**Comment by stof** [comment]
Most Mink steps are direct calls to the Mink Session or the WebAssert class. Thus, the DrupalContext extends from MinkContext, so it has access to the implementations of all steps and can call the methods directly

**Comment by jhedstrom** [comment]
@stof I realized I'd missed that as soon as I'd posted--the Drupal Extension now just calls those methods directly.

**Comment by rajeshtaneja** [comment]
@stof we are upgrading extension to behat 3 and this is a real show stopper for us.
In our case we have different plugin's and context. Also, it is hard for us to expect contributors to know all behat contexts, and use api's. With chained steps  it was easy to access steps from different behat contexts.

**Comment by stof** [comment]
@rajeshtaneja the issue is that chained steps are not the right way to provide reusability. And implementing them creates many weird issues (which is why this extension is not working currently)

**Comment by rajeshtaneja** [comment]
@stof thanks for the reply, I am not sure about implementation details, but surely it has benefits over api usage.
If you use chain steps for re-use, then hooks can be used to check before and after status and for profiling. Also, it is easy to debug if something gets wrong in large (chained) step

**Comment by stof** [comment]
triggering hooks for chained steps is precisely one of the pain point

**Comment by rajeshtaneja** [comment]
@stof I agree with that.
Certainly, you have good reasons for dropping this, but I will appreciate if you re-consider some solution (with limitation if needed). I am not sure, about how many users are affected with this decision, but surely one who are moving from chained steps to api have a big loss.
Also, upgrading to behat 3.x seems a step back with some of the major features being dropped like this.

I will try to go though the code to see if I can be of any help.

**Comment by stof** [comment]
I'm closing this issue. This experiment has been abandoned years ago.
